[/Script/GameplayTags.GameplayTagsList]

# Work Attitude
GameplayTagList=(Tag="Work.Kindling",DevComment="불 피우기 (화로, 요리)")
GameplayTagList=(Tag="Work.Watering",DevComment="관개 (물 주기, 제분기)")
GameplayTagList=(Tag="Work.Planting",DevComment="파종 (씨뿌리기)")
GameplayTagList=(Tag="Work.GeneratingElectricity",DevComment="발전 (전기 생성)")
GameplayTagList=(Tag="Work.Handiwork",DevComment="수작업 (제작대 작업)")
GameplayTagList=(Tag="Work.Gathering",DevComment="채집 (농작물 수확)")
GameplayTagList=(Tag="Work.Lumbering",DevComment="벌목 (나무 베기)")
GameplayTagList=(Tag="Work.Mining",DevComment="채굴 (광석 및 돌 캐기)")
GameplayTagList=(Tag="Work.MedicineProduction",DevComment="제약 (약 제작)")
GameplayTagList=(Tag="Work.Cooling",DevComment="냉각 (냉장고, 에어컨)")
GameplayTagList=(Tag="Work.Transporting",DevComment="운반 (아이템 상자 이동)")
GameplayTagList=(Tag="Work.Farming",DevComment="목장 (방목 시 아이템 드랍)")

# Skills
GameplayTagList=(Tag="Skill.Combat",DevComment="전투 보조 스킬")
 
GameplayTagList=(Tag="Skill.Mount.Ground",DevComment="지상 탑승 스킬")
GameplayTagList=(Tag="Skill.Mount.Flying",DevComment="공중 탑승(비행) 스킬")
GameplayTagList=(Tag="Skill.Mount.Water",DevComment="수상 탑승(수영) 스킬")

GameplayTagList=(Tag="Skill.Utility",DevComment="유틸리티 스킬")

# Status
GameplayTagList=(Tag="Status.Combat.Burn",DevComment="화상")
GameplayTagList=(Tag="Status.Combat.Freeze",DevComment="빙결")
GameplayTagList=(Tag="Status.Combat.Poison",DevComment="독")
GameplayTagList=(Tag="Status.Combat.Darkness",DevComment="암흑")
GameplayTagList=(Tag="Status.Combat.Paralysis",DevComment="감전(마비)")
GameplayTagList=(Tag="Status.Combat.Wet",DevComment="젖음")
GameplayTagList=(Tag="Status.Combat.Entangled",DevComment="덩굴 얽힘")
GameplayTagList=(Tag="Status.Combat.Quicksand",DevComment="모래 수렁")

GameplayTagList=(Tag="Status.Health.Hungry",DevComment="공복 (초기 허기)")
GameplayTagList=(Tag="Status.Health.Starvation",DevComment="굶주림")
GameplayTagList=(Tag="Status.Health.Cold",DevComment="감기/경상")
GameplayTagList=(Tag="Status.Health.Sprain",DevComment="염좌")
GameplayTagList=(Tag="Status.Health.Overeating",DevComment="과식증")
GameplayTagList=(Tag="Status.Health.Ulcer",DevComment="위궤양")
GameplayTagList=(Tag="Status.Health.Fracture",DevComment="골절")
GameplayTagList=(Tag="Status.Health.Weakness",DevComment="쇠약")
GameplayTagList=(Tag="Status.Health.Depression",DevComment="우울증")
GameplayTagList=(Tag="Status.Health.Homesick",DevComment="향수병")

GameplayTagList=(Tag="Status.Explo.Cold",DevComment="기온: 추위")
GameplayTagList=(Tag="Status.Explo.Heat",DevComment="기온: 더위")
GameplayTagList=(Tag="Status.Explo.Drowning",DevComment="질식/익사")
GameplayTagList=(Tag="Status.Explo.Encumbered1",DevComment="무게 초과 1단계")
GameplayTagList=(Tag="Status.Explo.Encumbered2",DevComment="무게 초과 2단계")
GameplayTagList=(Tag="State.Idle",DevComment="대기 중 (기본 상태)")
GameplayTagList=(Tag="State.Wander",DevComment="배회 중")
GameplayTagList=(Tag="State.Combat",DevComment="전투 중")
GameplayTagList=(Tag="State.Working",DevComment="작업 중")
GameplayTagList=(Tag="State.Sleeping",DevComment="수면 중")
GameplayTagList=(Tag="State.Flinch",DevComment="경직/피격 중")
